import type { Metadata } from "next";
import { Chonburi, Poppins } from "next/font/google";
import "./globals.css";

const chonburi = Chonburi({
  weight: "400",
  variable: "--font-chonburi",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "700"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chonburi.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
